fix Ruby 3 incompatibility when setting ENV because of how hash.each yielding changed
thinkific/cloud-secret-env pull request #10
Opened 2022-02-08 17:03 UTC by RyanNielson

Ruby 3 changed how `Hash#each` yields to lambdas which resulted in the error below when using this gem in a Ruby 3.1 app. This fix simply changes the lambda to expect a single 2-dimensional array that's the key value pair instead. This change was tested locally using `bundle exec rake` in both Ruby 2.6.6 and 3.1.0 and tests passed.

```
eval error: wrong number of arguments (given 1, expected 2)
  (rdbg)//Users/ryan/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/bundler/gems/cloud-secret-env-279d4027ab2e/lib/cloud_secret_env.rb:1:in `block in push_env!' 
  ```

**Changelog and discussion around the change:**
- https://rubyreferences.github.io/rubychanges/3.0.html#hasheach-consistently-yields-a-2-element-array-to-lambdas 
- https://bugs.ruby-lang.org/issues/16260

2022-02-08 17:19 UTC, kbluescode requested changes
One quick logic fix, then it should be good 👍

2022-02-08 17:19 UTC, kbluescode commented on lib/cloud_secret_env.rb
> +                  ->(pair) { ENV[pair[0]] = pair[1] unless ENV[pair[1]] }
The unless should use `pair[0]` since it's the key value.

The goal is to set the environment variable if it isn't already set.

```suggestion
                  ->(pair) { ENV[pair[0]] = pair[1] unless ENV[pair[0]] }
```

2022-02-08 17:28 UTC, RyanNielson commented on lib/cloud_secret_env.rb
> +                  ->(pair) { ENV[pair[0]] = pair[1] unless ENV[pair[1]] }
Good eye. I'll make that change and fix the tests to catch that.

2022-02-08 17:49 UTC, RyanNielson commented on lib/cloud_secret_env.rb
> +                  ->(pair) { ENV[pair[0]] = pair[1] unless ENV[pair[1]] }
Fixed this and updated/added some tests to cover override true and false configs.

2022-02-09 18:34 UTC, kbluescode approved these changes
LGTM :+1: :100: :rocket: :guitar:

2022-02-09 20:31 UTC, merged